services:
  ## Database service
  postgres:
    container_name: todo-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todo-db-volumes:/data/postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:5432
    networks:
      - todo-network
    restart: unless-stopped

  ## Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: todo-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_HOST: todo-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      AUTH_SECRET: ${JWT_SECRET}
      AUTH_EXPIRATION: ${JWT_EXPIRATION}

      SERVER_PORT: ${BACKEND_PORT}

      APPLICATION_NAME: ${APPLICATION_NAME}
      CONTEXT_PATH: ${CONTEXT_PATH}
    ports:
      - ${BACKEND_PORT}:9100
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network

  ## Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: todo-frontend
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  todo-db-volumes:
    driver: local