apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app

data:
  # Database
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: todos

  # Backend
  SERVER_PORT: "9100"
  AUTH_EXPIRATION: "86400000"
  APPLICATION_NAME: todo-backend
  CONTEXT_PATH: /api

  # Frontend
  FRONTEND_PORT: "80"