spring:
  application:
    name: todo-api

  datasource:
    url: jdbc:postgresql://localhost:5433/todo_db
    username: todo_dev
    password: todoDev@123
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    jwt:
      secret: 4f6a6d784b50733356367839244226452948404d635166546a576e5a7234753778
      expiration: 86400000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info