spring:
  application:
    name: todo-api

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: todoDB
    password: todoDB@123

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info